Revert "Implement a new kind of Pass: dynamic pass pipeline"
This reverts commit 8b8d68ab1d69828925e34e4f6a7e52a0798606c4.

Test  mlir/test/Pass:dynamic-pipeline-fail-on-parent.mlir.test fails
when run with ASAN:

ERROR: AddressSanitizer: stack-use-after-scope on address ...

Reviewed By: bkramer, pifon2a

Differential Revision: https://reviews.llvm.org/D88079