Revert "[MLIR][SPIRV] Start module combiner."
This reverts commit fd834d4ed561a2bfa6eada4f21ae547baa17c3c1.

Shared libs build is broken linking lib/libMLIRSPIRVModuleCombiner.so:

```
ModuleCombiner.cpp:
  undefined reference to `mlir::spirv::ModuleOp::addressing_model()
```

https://buildkite.com/mlir/mlir-core/builds/8988#e3d966b9-ea43-492e-a192-b28e71e9a15b