Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit dda88ac2b263b4cd7bc4c7aad3c83a7d8451fb70. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```