Revert "[ADT] Support const-qualified unique_functions"
This reverts commit 14d1cf227f68b906c14d2db84a1d65bea2e486fb.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;