Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit 39990af8ced5688303ef3ed0a16ee302341b4ee3 because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }