Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit 38a309efebd98ac8afadbf4aa3172e9b85b09804.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found