evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit 4b972e649dcbb250a9b65d96bfd369f13630e17b.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'