[mlir] Fix a warning
This patch fixes:

  mlir/lib/Dialect/Linalg/Transforms/HoistPadding.cpp:37:13: error:
  unused function 'debugPrintLoopInShortForm'
  [-Werror,-Wunused-function]