Revert "[MLIR] Expose `getAsValues` in `StaticValueUtils.h` (NFC)"
This reverts commit a4a3daaf7371f1cfc4d551e21fca44205cf3ce06.

It fails with a linking errors: `undefined reference to
`mlir::getValueOrCreateConstantIndexOp` in `libMLIRDialectUtils`.