Revert "[Hexagon] Add instruction definitions for Hexagon v71, v71t, and v73"
This reverts commit bef827abb606e8490014e34f24e4a22c78601df9.

The commit caused:

clang/include/clang/Basic/BuiltinsHexagonDep.def:1896:69: error: use of undeclared identifier 'HVXV73'
TARGET_BUILTIN(__builtin_HEXAGON_V6_vadd_sf_bf, "V32iV16iV16i", "", HVXV73)

when building `clang`.