Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit 21218158849a5f46e918d19982ab53889cae432f.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'