[NVPTX] Temporary disable dwarf-file-dir.ll on Windows
The test was added in D121299 and it fails on Windows:

    error: CHECK-NODIR: expected string
    not found in input
    ; CHECK-NODIR: .file {{[0-9]+}} "/tmp/dbginfo/a/a.cpp"
		   ^
    <stdin>:1:1: note: scanning from here
    //
    ^
    <stdin>:25:2: note: possible intended match here
     .file 1 "/tmp/dbginfo/a\\a.cpp"