Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit fefae0f1ffa2f87d0bf662bd6f5d72d2d0b0203a.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {