Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit 0ccc34e469193fffb11df945247b580aa2e67945 and
d39a803bffa9412c0d6388651ea0353f8087eb7d.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!