Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit cc2acec35a66bb966b626a0007451c94659210d7.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.