Revert "Use-after-return sanitizer binary metadata"
This reverts commit 45da1832ce45c303a60ceb81dbedf02ecacd198e.

This patch results in:

  llvm/lib/CodeGen/SanitizerBinaryMetadata.cpp:57:17: error: no member
  named 'size' in 'llvm::MDTuple'