Revert "lit: revert 000913ea0e0c53a357f74ea5b5346caf01afa8c9"
This reverts commit f61dd4ecd665740a0838d831671a615d4c27b0e1.

Causing messages like:

  File "...\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74