Revert "Threading: Convert Optional to std::optional"
This reverts commit 004156804e6b9d7f6544ab6474ff5011bc4ccfaf.

This commit breaks the build for BOLT:
  bolt/lib/Profile/DataAggregator.cpp:264:66: error: no viable
  conversion from 'Optional<StringRef>[3]' to
  'ArrayRef<std::optional<StringRef>>'